[package]
name = "ya-gist"
version = "0.1.0"
edition = "2018"
description = "GIST Administrative Automation Program"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
